import Head from 'next/head'
import Layout from '@/components/layout/Layout'
import Poster from '@/components/shared/Poster'
import { useQuery } from "react-query";
import { getPopularMovies } from "@/pages/api/rq-tmdb";

export default function MoviesPage() {
    const { isLoading, isError, data, error } = useQuery(
        "popularMovies",
        () => getPopularMovies(1)
      );
    
      if (isLoading) return <div>Loading...</div>;
      if (isError) return <>Error: {error}</>

  return (
    <>
      <Layout>
            <Head>
              <title>Demo</title>
              <meta name="description" content="Generated by create next app" />
              <meta name="viewport" content="width=device-width, initial-scale=1" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='min-h-screen bg-gray-700'>
                <div className='flex flex-col justify-center items-center'>
                    <p className='text-white font-bold text-4xl py-5'>Popular Movies</p>
                    <div className="flex flex-wrap justify-center gap-3">
                        {data.results.map((movie: any) => (
                            <div key={movie.id}>
                                <Poster
                                    link={`/movies/${movie.id}`}
                                    poster_path={`https://image.tmdb.org/t/p/w500${movie.poster_path}`}
                                    title={movie.title}
                                    release_date={movie.release_date}
                                    overview={movie.overview}
                                />
                            </div>
                        ))}
                    </div>
                </div>
            </main>
        </Layout>
    </>
  )
}
