import { useEffect, useState } from 'react';
import { fetchData } from '@/pages/api/api';

import Head from 'next/head'

import Layout from '@/components/layout/Layout'

type DataType = {
    id: number,
    title: string
  };

const Page = () => {
const [data, setData] = useState<DataType[]>([]);

  useEffect(() => {
    const getData = async () => {
      const result = await fetchData();
      setData(result);
    };

    getData();
  }, []);

  return (
    <>
        <Layout>
            <Head>
                <title>Demo</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='bg-gray-800'>
                <div className='flex flex-col items-center py-10 max-w-2xl mx-auto'>
                <h1 className='text-white font-bold text-4xl'>Basic Axios Data Fetching</h1>
                    <ul className='text-red-600 flex flex-wrap'>
                        {data.slice(0, 30).map((item) => (
                        <li key={item.id}>
                            <div className='p-2 bg-gray-200 rounded-sm m-1 w-[96px]'>
                            {item.id}. <br/>
                            <div className='line-clamp-3'>
                            {item.title}
                            </div>
                            </div>
                        </li>
                        ))}
                    </ul>
                </div>
            </main>
        </Layout>
    </>
  );
};

export default Page;
